# Generated by Django 5.1.7 on 2025-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0003_rename_order_by_articlestatictagsindexpage_order_by_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepageimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If this image is the featured image to be used in social media links and similar contexts. Only one should be selected. ', verbose_name='is featured'),
        ),
    ]
