# Generated by Django 5.1.7 on 2025-03-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0005_articlestatictagsindexpage_full_body_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatictagsindexpage',
            name='apply_special_formatting',
        ),
        migrations.AlterField(
            model_name='articlestatictagsindexpage',
            name='full_body_groups',
            field=models.CharField(blank=True, default='1', help_text="A comma separated list of the tag group numbers for which the full body instead of summary should be shown in an index page. '1' is the first group.  ex: '1,2'", max_length=30, verbose_name='full body groups'),
        ),
    ]
