# Generated by Django 5.1.7 on 2025-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0006_remove_articlestatictagsindexpage_apply_special_formatting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestatictagsindexpage',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom css to be added to the html head section when this page is displayed'),
        ),
    ]
