# Generated by Django 5.1.7 on 2025-04-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0007_articlestatictagsindexpage_custom_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='show_bottombar',
            field=models.BooleanField(default=False, help_text='If the bottom sidebar should be shown'),
        ),
        migrations.AddField(
            model_name='sitetemplatesettings',
            name='show_topbar',
            field=models.BooleanField(default=False, help_text='If the top sidebar should be shown'),
        ),
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='show_leftbar',
            field=models.BooleanField(default=False, help_text='If the left sidebar should be shown'),
        ),
        migrations.AlterField(
            model_name='sitetemplatesettings',
            name='show_rightbar',
            field=models.BooleanField(default=False, help_text='If the right sidebar should be shown'),
        ),
    ]
