# Generated by Django 5.1.7 on 2025-04-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0008_sitetemplatesettings_show_bottombar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebararticlepage',
            name='show_title',
            field=models.BooleanField(default=True, help_text='If the title should be shown'),
        ),
    ]
