# Generated by Django 5.1.7 on 2025-04-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0009_sidebararticlepage_show_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindexpage',
            name='order_by_field',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='order_by_date',
        ),
        migrations.RemoveField(
            model_name='articlestatictagsindexpage',
            name='order_by_field',
        ),
        migrations.RemoveField(
            model_name='sidebararticlepage',
            name='order_by_date',
        ),
        migrations.RemoveField(
            model_name='sidebarpage',
            name='order_by_field',
        ),
    ]
