# Generated by Django 5.1.7 on 2025-05-31 09:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('webikwa', '0010_remove_articleindexpage_order_by_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcalendarPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('data', models.TextField(blank=True, help_text='The ICS data', verbose_name='body')),
                ('source', models.URLField(help_text='The ical to get the data from', verbose_name='source')),
                ('uid_links', models.TextField(blank=True, help_text='A json format list cross referencing uids and links', verbose_name='uids > links')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='basearticlepage',
            name='calendar_format',
            field=models.CharField(choices=[('EVLS', 'event list'), ('MMON', 'm-s month grid'), ('SMON', 's-s month grid'), ('DTLS', 'date list')], default='EVLS', help_text='The format for how the events are displayed', max_length=4, verbose_name='calendar format'),
        ),
        migrations.AddField(
            model_name='basearticlepage',
            name='ical_start_span_count',
            field=models.CharField(blank=True, default='-1,3660', help_text='Comma separated numbers representing the number of days to the starting date (can be negative), the number of days from the starting date to the ending date, and the max number of events to return', max_length=20, verbose_name='start,span,count'),
        ),
        migrations.AddField(
            model_name='basearticlepage',
            name='calendars',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='webikwa.icalendarpage'),
        ),
    ]
