# Generated by Django 5.1.7 on 2025-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0011_icalendarpage_basearticlepage_calendar_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icalendarpage',
            name='data',
            field=models.TextField(blank=True, help_text='The ics data. If source is filled in, this will be overwritten. If you wish to edit this field, ensure the source field is blank', verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='icalendarpage',
            name='source',
            field=models.URLField(blank=True, help_text='The ics source which will copied to the data', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='icalendarpage',
            name='uid_links',
            field=models.TextField(blank=True, help_text='A json format list cross referencing uids from the data and links. ex: "{ 483jfjc8@thiscalendersource.com":"https://thiswebsite.com/articles/somearticle",{ 984jf8vdk@thiscalendarsource.com":"https://somewebsite.com/someevent.html"}', verbose_name='uids > links'),
        ),
    ]
