# Generated by Django 5.1.7 on 2025-05-31 21:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0012_alter_icalendarpage_data_alter_icalendarpage_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icalendarpage',
            name='uid_links',
        ),
        migrations.CreateModel(
            name='IcalendarLinkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(help_text='The UID of the event from ics data', max_length=80)),
                ('url', models.URLField(blank=True, help_text='The URL')),
                ('icalendar', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_links', to='webikwa.icalendarpage')),
            ],
        ),
    ]
