# Generated by Django 5.1.7 on 2025-05-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0013_remove_icalendarpage_uid_links_icalendarlinkpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icalendarlinkpage',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='icalendarlinkpage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
