# Generated by Django 5.1.7 on 2025-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0015_basearticlepage_calendar_dt_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icalendarpage',
            name='is_safe',
            field=models.BooleanField(default=False, help_text="If it's certain that the code from the remote calendar is safe.  This can be dangerous.  Know that you can trust the source before enabling", verbose_name='is safe'),
        ),
    ]
