# Generated by Django 5.1.7 on 2025-06-17 21:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0016_icalendarpage_is_safe'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcalendarBlockPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('uid', models.CharField(help_text='The UID of the event to block, from ics data', max_length=120)),
                ('icalendar', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_blocks', to='webikwa.icalendarpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
