# Generated by Django 5.2.4 on 2025-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webikwa', '0019_remove_basearticlepage_calendar_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icalcombinerpage',
            name='calendar_format',
            field=models.CharField(choices=[('DTLS', 'date list')], default='DTLS', help_text='(choices unavailable for now) The format for how the events are displayed', max_length=4, verbose_name='calendar format'),
        ),
    ]
